FROM node:7.7.3-slim

RUN apt-get update && \
    apt-get install git-core -y

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN npm install -g nodemon
RUN npm install -g micro

EXPOSE 80

ENV NODE_ENV development

CMD nodemon --watch ./packages/server --exec 'cd ./packages/server/ && npm start -- -p 80'
