module.exports = profile => ({
  id: profile.id,
  avatarUrl: profile.avatar_https,
  avatar_https: profile.avatar_https,
  type: profile.service,
  handle: profile.service_username,
  pendingCount: profile.counts.pending,
  sentCount: profile.counts.sent,
  timezone: profile.timezone,
  timezone_city: profile.timezone_city,
  schedules: profile.schedules,
  service: profile.service,
  service_type: profile.service_type,
  serviceUsername: profile.service_username,
  service_username: profile.service_username,
  formatted_username: profile.formatted_username,
  subprofiles: profile.subprofiles,
  disabled: profile.disabled,
  business: profile.business,
  default: profile.default,
  open: false,
});
